# docker-compose.yml
version: '2.8'

services:
  api:
    build: . # Build the image from the Dockerfile in the current directory
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=admin
    depends_on:
      - mongo
      - redis
  redis:
    image: redis:7.4
    container_name: api-redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:api-redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
  mongo:
    image: mongo:latest 
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - TZ=Asia/Phnom_Penh

volumes:
   mongo-data: